import = ["/home/pldcanfly/.config/alacritty/themes/carbonfox.toml"]

[mouse]
hide_when_typing = false

[window]
dimensions = { columns = 200, lines = 50 }
decorations = "None"
padding = { x = 10, y = 10 }
