[colors.primary]
background = '#0a1126'
foreground = '#e1e7f5'

[colors.cursor]
text = '#0f1b40'
cursor = '#e1e7f5'

[colors.vi_mode_cursor]
text = '#0a1126'
cursor = '#99b6f2'

[colors.search.matches]
foreground = '#0f1b40'
background = '#4e6ba6'

[colors.search.focused_match]
foreground = '#0f1b40'
background = '#99b6f2'

[colors.footer_bar]
foreground = '#0f1b40'
background = '#e3e4e8'

[colors.hints.start]
foreground = '#0f1b40'
background = '#5581d9'

[colors.hints.end]
foreground = '#0f1b40'
background = '#5581d9'

[colors.selection]
text = '#0a1126'
background = '#99b6f2'


[colors.normal]
black   = '#0f1b40'
red     = '#d98886'
green   = '#86b393'
yellow  = '#e3cfa8'
blue    = '#5581d9'
magenta = '#bda6db'
cyan    = '#99b6f2'
white   = '#e1e7f5'


[colors.bright]
black   = '#212c4d'
red     = '#e69e9c'
green   = '#9ec4aa'
yellow  = '#f0e2c2'
blue    = '#779beb'
magenta = '#d2c2e8'
cyan    = '#b5ccf7'
white   = '#f2f5fc'


[colors.dim]
black   = '#0f1b40'
red     = '#d98886'
green   = '#86b393'
yellow  = '#e3cfa8'
blue    = '#5581d9'
magenta = '#bda6db'
cyan    = '#99b6f2'
white   = '#e1e7f5'
