#!/usr/bin/env bash

# Status bar style
set -g status-position top
set -g status-style bg=default,fg=#d4be99

set -g 'status-format[1]' ''
set -g status 2

set -g status-left-length 150
set -g status-left '#[bold,reverse]  #S '

# Right side of status bar
set -g status-right-length 150
set -g status-right '#[bold] 󱑂 #{continuum_status}  #[bold] #(~/.config/tmux/scripts/git-status.sh) '
# Window titles
# Window list style
set -g status-justify centre
setw -g window-status-style bold
setw -g window-status-format '   #W (#I) '

setw -g window-status-current-style bold,reverse
setw -g window-status-current-format '  #W (#I) '

# Pane border color
set -g pane-border-style fg=white
set -g pane-active-border-style fg=yellow

# Message text color
set -g message-style fg=black,bg=red,bold

# Command prompt text color
set -g message-command-style fg=#141516,bg=colour124,bold

# # Colors (Gruvbox Material Hard Dark)
#
# # Default colors
# [colors.primary]
# background = '#141617'
# foreground = '#d4be98'
#
# # Normal colors
# [colors.normal]
# black   = '#32302f'
# red     = '#ea6962'
# green   = '#a9b665'
# yellow  = '#d8a657'
# blue    = '#7daea3'
# magenta = '#d3869b'
# cyan    = '#89b482'
# white   = '#d4be98'
#
# # Bright colors (same as normal colors)
# [colors.bright]
# black   = '#32302f'
# red     = '#ea6962'
# green   = '#a9b665'
# yellow  = '#d8a657'
# blue    = '#7daea3'
# magenta = '#d3869b'
# cyan    = '#89b482'
# white   = '#d4be98'
