# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = "$hostname$directory$nodejs\n$character"

[character]
success_symbol = '[\$](bold blue)'
error_symbol = '[](bold red)'
vimcmd_symbol = '[](bold purple)'
vimcmd_replace_one_symbol = '[](bold purple)'
vimcmd_replace_symbol = '[](bold purple)'
vimcmd_visual_symbol = '[](bold purple)'

[hostname]
ssh_only = false
format = '[$hostname](yellow bold) '

[directory]
truncate_to_repo = true
style = 'blue'

[nodejs]
format = '[$symbol($version)]($style)'
