# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = "$username$directory$nodejs\n$character"

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[username]
style_user = 'white'
style_root = 'red bold'
format = '[$user]($style) '
show_always = true
#
[directory]
truncate_to_repo = true
style = 'blue'


[nodejs]
format = '[$symbol($version)]($style)'
